### ISSUE TITLE
Ruby capstone Kanban persentation

### ISSUE THREAD

**Issue by husush23** [husush23/Capstone--4#25]
### In this issue, we are displaying  the Kanban we created to work on the catalog project(Ruby capstone)
We are a group of three persons, @husush23, @Katended  and @Peter-Dumbari. Each member is assigned specific tasks and also there are group tasks we will do together. you can see on the issues page how every member is assigned per task. 
Here is our [Kanban ](https://github.com/users/husush23/projects/5/views/1) project created.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @husush23, @Katended and @Peter-Dumbari,

✔️ Tasks are complete and well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
